{{- if and (eq .Values.controlPlane.authMode "token") (not .Values.controlPlane.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-opamp-supervisor.controlPlaneSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-opamp-supervisor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.controlPlane.tokenKey }}: {{ .Values.controlPlane.token | quote }}
{{- end }}
